### ISSUE TITLE
Attachments inserted into preview of text emails

### ISSUE THREAD

**Issue by bbuchalter** [basecamp/mail_view#38]
This does not happen in the HTML version.

![Screenshot from 2013-03-31 12:38:20](https://f.cloud.github.com/assets/540762/322036/78d1410c-9a21-11e2-8591-21a1eb4a4f7b.png)

**Comment by tylercollier** [comment]
I'm seeing this too

**Comment by tylercollier** [comment]
@bbuchalter, actually, I'm seeing the exact same output in the html version. The only solution I have is to remove my text version during preview, and then it works fine. Have you tried it with an HTML part and TEXT part?

**Comment by isaacsanders** [comment]
We are seeing this as well.

**Comment by jeremy** [comment]
This happens when you have a multipart message, but not multipart/alternative, and the text/plain part doesn't come first. When no content type is specified, mailview uses the first mime part by default.

Fixing this to use either the first mime part of a multipart/alternative part or the first text part.

**Comment by tylercollier** [comment]
I updated to the latest version, 2.0.1, and it works as expected. I did not have to make any other changes, like the ordering of multipart parts. Awesome!
